# Project information
site_name: ORAYLIS - Continuous Deployment mit Azure DevOps

# Repository
repo_name: 'Content_Dokumentation'
repo_url: 'https://github.com/zyeiy2/Content_Dokumentation/'

theme:
  name: material
  font:
    text: Arial
  features:
    - header.autohide 
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - navigation.top
    - navigation.footer
    - toc.integrate 
    - search.share
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
  language: de
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: oraylis
      toggle:
        icon: material/brightness-auto
        name: Automatic Mode
    - media: "(prefers-color-scheme: light)"
      scheme: oraylis
      toggle: 
        icon: material/eye
        name: Light mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/eye-outline
        name: Dark mode
  logo: stylesheets/favicon-76.png

plugins: 
  - search
  - glightbox
  - mermaid2:
      version: 1.2.1

extra_css:  
  - stylesheets/extra.css

nav:
  - Into: 
    - Start: "Intro/Start.md"
    - Agenda: "Intro/Agenda.md"
    - Azure DevOps: "Intro/Azure DevOps.md"
    - CI CD: "Intro/CI CD.md"
    - ORAYLIS: "Intro/ORAYLIS.md"
  - YAML:
    - YAML Schema: "YAML/YAML Schema.md"
    - YAML Schemareferenz: "YAML/YAML Schemareferenz.md"
  - Hello World: 
    - Eigenes Projekt erstellen: "Hello World/Eigenes Projekt erstellen.md"
    - Agents: "Hello World/Agents.md"
    - Verzeichnisse: "Hello World/Verzeichnisse.md"
    - Tasks: "Hello World/Tasks.md"
    - Veröffentlichen von Artefakten: "Hello World/Veröffentlichen von Artefakten.md"
  - Variablen und Secrets:
    - Variablen und Secrets: "Variablen und Secrets/Variablen und Secrets.md"
    - Approvals: "Variablen und Secrets/Approvals.md"
  - Trigger: 
    - Trigger: "Trigger/Trigger.md"
  - Konsumieren von Artefakten:
    - Konsumieren von Pipeline Artefakten: "Konsumieren von Artefakten/Konsumieren von Pipeline Artefakten.md"
  - Templates:
    - Templates: "Templates/Templates.md"
  - Aufgabe: 
    - Aufgabe: "Aufgabe/Aufgabe.md"
  - Module: 
    - Selbstgehostete CI CD Agents: "Selbstgehostete CI CD Agents/Selbstgehostete CI CD Agents.md"
    - Einordnung in Azure DevOps: "Selbstgehostete CI CD Agents/Einordnung in Azure DevOps.md"
    - Human Agents: "Selbstgehostete CI CD Agents/Human Agents.md"
    - Azure Resources: "Selbstgehostete CI CD Agents/Azure Resources.md"
    - Code: "Selbstgehostete CI CD Agents/Code.md"
    - HandsOn: "Selbstgehostete CI CD Agents/HandsOn.md"

  - Outro: 
    - Outro: "Outro/Outro.md"
    - Schulungen: "Outro/Schulungen.md"
    - Links: 
      - Lösung: "Outro/Links/Lösung.md"
