# Project information
site_name: ORAYLIS - Continuous Deployment mit Azure DevOps

# Repository
repo_name: 'Content_Dokumentation'
repo_url: 'https://github.com/zyeiy2/Content_Dokumentation/'

theme:
  name: material
  font:
    text: Arial
  features:
    - header.autohide 
  language: de
  palette:
    scheme: oraylis
  logo: stylesheets/favicon-76.png

extra_css:  
  - stylesheets/extra.css
