# Project information
site_name: ORAYLIS - Continuous Deployment mit Azure DevOps

# Repository
repo_name: 'Content_Dokumentation'
repo_url: 'https://github.com/zyeiy2/Content_Dokumentation/'

theme:
  name: material
  font:
    text: Arial
  features:
    - header.autohide 
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - navigation.top
  language: de
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: oraylis
      toggel: 
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggel:
        icon: material/weather-sunny
        name: Switch to light mode
  logo: stylesheets/favicon-76.png

extra_css:  
  - stylesheets/extra.css
